version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "trunk"
    labels:
      - "maven dependencies"
    ignore:
      - dependency-name: 'org.apache.maven.plugins:maven-shade-plugin'
        versions: ['>=3.5.1']
