name: PatheticTest
version: '${project.version}'
main: de.metaphoriker.pathetic.example.PatheticPlugin
api-version: 1.21
authors:
  - olijeffers0n
  - Metaphoriker

commands:
  pathetic:
    description: What a pathetic command
    aliases:
      - path
      - pathfinder
